
# PATHS
train_dataset: ./data/train
#validation_dataset: ./data/validation
validation_dataset: ./data/test
predict_dataset: ./data/test
#load_model_path: ./CheckPoint/experiment_2022_08_24_19_44_26/ckpt/weights.08-0.329
output_path: ./
additional_functions_file: ./additional_functions.py

# OPTIMIZATION OPTIONS
loss: BinaryCrossentropy
#loss: CustomLoss
optimizer:
  type: Adam
  learning_rate: 0.000403285
  clipnorm: 1.0
  clipvalue: 0.5
metrics: [BinaryAccuracy, Precision, Recall]



# TRAINING OPTIONS
batch_size: 32 #1
epochs: 500
epoch_size: 4500
#shuffle_training_set: True
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 500
val_frequency: 1
execute_gpu: False
batch_norm: mean
initial_epoch: 0
